### PR TITLE
import PropTypes from prop-types instead of from React

### PR DESCRIPTION
**Pull request by nassimbenkirane**
Hi there, Thanks for the good work with HoverIntent 👍 

I was trying to migrate my app to React 16 beta today, and now importing PropTypes from React directly is no longer a warning, instead it throws an error.

This pull request to add a dependency to the 'prop-types' package and use this instead of React.PropTypes

Is there something else I need to do for this PR ?

### CODE REVIEW

**Comment by nerdchacha** [comment]
Hi @nassimbenkirane

Apologies for the delayed response. Glad that you found this module helpful and i really appreciate the effort to make this better.
Would it be possible for you to only create the PR with the changes in the source file and not include the build in the PR?

Thanks

**Comment by nassimbenkirane** [comment]
Hi @nerdchacha 

I was used to using HoverIntent with jQuery and wanted this for my React Components. I'm glad I didn't have to write the code myself :)

Regarding this P.R., I have [b34501a](https://github.com/nerdchacha/react-hoverintent/pull/4/commits/b34501a6755a88205414e0fe3db2d8c1ca5b097d) this commit that removes the modifications in `dist`. Unfortunately, I can't change the source of the PR to point to that commit, should I publish another PR ? (I would like to keep `zenchef:master` at least until next week as is because it's what we're using right now) 

Anyway it's a very simple modification, so if you wish to close the PR and do the changes yourself, maybe it's easier ^^

**Comment by nerdchacha** [comment]
Sounds good.
Its a bit for me here. I should be able to release a patch with the changes maybe tomorrow morning my time and will close this PR once everything looks okay.
Hope that will help.
Will keep you posted

**Comment by nerdchacha** [comment]
@nassimbenkirane 
`v0.0.10` should have the changes now.
Please confirm if everything works fine before i close this PR

**Comment by nassimbenkirane** [comment]
Hi @nerdchacha, Thanks for the modification !
It's now working fine with react 16 :)

**Pull request closed without merging**
